### PR TITLE
Ansible bug no newline with lookup. 

### LINKED ISSUE #9: Newline char stripped from EOF on deployed files
There's an Ansible bug in `lookup` which means files deployed using this mechanism have `rtrim` applied, and so are missing the Newline char `0x0a` 

Ref: https://github.com/ansible/ansible/issues/30829

```
2018-10-09 09:52 LS27172:~ kenny$ diff -y -W 190 <(hexdump -C from-ansible-role-ssl-certificate.crt) <(hexdump -C from-original-file.crt)  | tail -n 3
00001a00  2d 45 4e 44 20 43 45 52  54 49 46 49 43 41 54 45  |-END CERTIFICATE|                  00001a00  2d 45 4e 44 20 43 45 52  54 49 46 49 43 41 54 45  |-END CERTIFICATE|
00001a10  2d 2d 2d 2d 2d                                    |-----|                           | 00001a10  2d 2d 2d 2d 2d 0a                                 |-----.|
00001a15                                                                                      | 00001a16
2018-10-09 09:52 LS27172:~ kenny$
```

### PR DESCRIPTION
**Pull request by kennethgillen**
Mainly an issue with the README and Molecule test.

Ansible bug is https://github.com/ansible/ansible/issues/30829

--fixes #9

### CODE REVIEW

**Comment by manics** [comment]
Have you got a link to the Ansible bug report?

**Comment by kennethgillen** [comment]
https://github.com/ansible/ansible/issues/30829

**Comment by manics** [comment]
Looks OK as a docs change. Can you confirm you've run this configuration for real somewhere?

**Comment by kennethgillen** [comment]
I've not tried this with the `ansible-role-ssl-certificate` yet, but it does fix the issue when going from `lookup` directly to disk.

I notice `ansible-role-ssl-certificate` goes further and does some base64 encoding, so it may not work after that. I'll be trying this PR locally with this role imminently.

**Comment by kennethgillen** [comment]
@manics  - further fix - the additional trim on the combined and bundled content was creating files with no Newline at EOF.

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [ANSIBLE-merge#466](https://ci.openmicroscopy.org/job/ANSIBLE-merge/466/). See the [console output](https://ci.openmicroscopy.org/job/ANSIBLE-merge/466/consoleText) for more details.
Possible conflicts:
  - PR #8 sbesson 'Molecule2'
    - molecule.yml

--conflicts

**Comment by kennethgillen** [comment]
Deployed to `ome-www-dev` and newlines are good.

**Review by manics — APPROVED** [review]
Looks OK to me

**Pull request merged**
