### PR TITLE
Modify default path to use /etc/ssl/localcerts

### PR DESCRIPTION
**Pull request by sbesson**
See https://github.com/openmicroscopy/prod-playbooks/pull/51#discussion_r177001176

Updates the default paths of the role to use `/etc/ssl/localcerts`

### CODE REVIEW

**Comment by kennethgillen** [comment]
@sbesson  - will it create the directory if it doesn't already exist, and with the correct permissions?

**Comment by sbesson** [comment]
@kennethgillen that's certainly my expectation and it should be tested by `molecule`. Maybe worth expanding the `test_default` to cover this?

**Comment by sbesson** [comment]
Actually, looking at the details https://github.com/openmicroscopy/ansible-role-ssl-certificate/pull/5/files#diff-11bf69e44d3f1f5ab417c15f43b6c1b7R10 already tests the file existence as it needs to access the cert file and the local directory does not exist on the base image. Re `correct permissions`, what are your expectations?

**Comment by kennethgillen** [comment]
@sbesson  - perhaps folder perms don't matter, as long as the private key is only readable by `root`.

**Comment by sbesson** [comment]
Sorry forgot to answer https://github.com/openmicroscopy/ansible-role-ssl-certificate/pull/5#issuecomment-379284655. I think the permissions issue is  handled in the role tasks e.g.

- https://github.com/openmicroscopy/ansible-role-ssl-certificate/blob/master/tasks/main.yml#L37 for the public cert
- https://github.com/openmicroscopy/ansible-role-ssl-certificate/blob/master/tasks/main.yml#L53 for the private key
...

I reflected the state of the proposed changes here in https://github.com/openmicroscopy/prod-playbooks/pull/51. Running the playbook against the `ome-www-dev` server gives:

```
[sbesson@ome-www-dev localcerts]$ ls -alh
total 32K
drwxr-xr-x  2 root root 4.0K Apr 10 17:32 .
drwxr-xr-x. 3 root root 4.0K Apr 10 17:32 ..
-r--r--r--  1 root root 6.6K Apr 10 17:32 bundled.crt
-r--r--r--  1 root root 4.7K Apr 10 17:32 intermediate.crt
-r--r--r--  1 root root 1.9K Apr 10 17:32 server.crt
-r--------  1 root root 1.7K Apr 10 17:32 server.key
```

**Pull request merged**
